version: 2.1

jobs:

  build:

    docker:
    - image: cimg/base:current

    resource_class:
      small

    steps:
    - setup_remote_docker:
        docker_layer_caching: false

    - checkout
    
    - run:
        name: Build Docker Image
        command: |
          docker build -t dpkg-build .

    - run:
        name: View build history
        command: |
          docker image history --no-trunc dpkg-build

    #- run:
        #name: Upload Docker Image
          # docker tag dpkg-build s0600204/dpkg-build
          # docker login -u $DOCKER_USER -p $DOCKER_PASS
          # docker push s0600204/dpkg-build
